# Default values for kaj-dev-core-srvc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  name: prd-pena-web
  namespace: prd
  
replicaCount: 1

image:
  repository: meongbego/pena-web
  pullPolicy: IfNotPresent
  tag: "prd"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  priority: 10
  domain: pena.penpod.id
  className: ingress
  ssl: false
  ssl_redirect: false
  force_ssl_redirect: false

resources:
  requests:
    cpu: 100m
    memory: 1024Mi
  limits:
    cpu: 2000m
    memory: 4096Mi

hpa:
  enabled: false
  spec:
    minReplicas: 1
    maxReplicas: 2
    memory:
      averageUtilization: 80
    cpu:
      averageUtilization: 80